spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    user:
      name: root
      password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
